name: flutter_application_1
description: "A new Flutter project."

# Evita que el paquete se publique accidentalmente en pub.dev
publish_to: 'none'

# Versión de la aplicación
version: 1.0.0+1

# Entorno requerido
environment:
  sdk: ^3.5.2

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  logger: ^2.5.0
  google_sign_in: ^6.2.2
  fluent_ui: ^4.9.2
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  intl: ^0.19.0

# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # Ruta del ícono

# Configuración de Flutter
flutter:
  uses-material-design: true

  # Recursos de imagen
  assets:
    - assets/logo_utem.png
